yarnPath: .yarn/releases/yarn-2.1.1.cjs

packageExtensions:
  "@apextoaster/js-utils@*":
    dependencies:
      "@types/node": "*"
      noicejs: "*"
  "@apextoaster/js-yaml-schema@*":
    dependencies:
      "@types/js-yaml": "*"
      "@types/node": "*"
  "@types/chai-as-promised@*":
    dependencies:
      chai: "*"
  "@types/sinon-chai@*":
    dependencies:
      chai: "*"
      sinon: "*"
  eslint-plugin-import@*:
    dependencies:
      eslint-import-resolver-node: "*"
  rollup@*:
    dependencies:
      source-map-support: "*"